spring:
    application:
        name: springcloudkubernetes
    cloud:
        kubernetes:
            config:
                name: springcloudkubernetes
                namespace: cp
                sources:
#                    # Spring Cloud Kubernetes will lookup a ConfigMap named c1 in namespace default-namespace
#                    - name: c1
#                    # Spring Cloud Kubernetes will lookup a ConfigMap named default-name in whatever namespace n2
#                    - namespace: n2
#                    # Spring Cloud Kubernetes will lookup a ConfigMap named c3 in namespace n3
                    - namespace: cp
                      name: springcloudkubernetes
logging.level.org.springframework.cloud.kubernetes: trace