kind: Service
apiVersion: v1
metadata:
  name: springcloudkubernetes
  annotations:
    fabric8.io/ingress.path: /
    fabric8.io/ingress.annotations: |-
      ingress.kubernetes.io/rewrite-target: /
      ingress.kubernetes.io/force-ssl-redirect: true
      kubernetes.io/ingress.class: internal-ingress
      forecastle.stakater.com/expose: true
  labels:
      expose: "true"
spec:
  selector:
    app: springcloudkubernetes
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080